### ISSUE TITLE
Crash when starting Safehouse

### ISSUE THREAD

**Issue by Skyfry428** [DrNewbie/Safehouse-Plus#1]
Application has crashed: C++ exception
bad allocation

---

Callstack:

```
                     ntdll  (???)     ???                                                 
                     ntdll  (???)     ???                                                 
                       ???  (???)     ???                                                 
                       ???  (???)     ???                                                 
                       ???  (???)     ???                                                 
                       ???  (???)     ???                                                 
                       ???  (???)     ???                                                 
                     ntdll  (???)     ???                                                 
```

---

Current thread: Renderer

---

System information:
    Application version : 1.55.37
    CPU : Intel(R) Core(TM) i5 CPU M 480 @ 2.67GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
    DirectX : 12.0 
    GPU : Intel(R) HD Graphics / nvumdshim.dll[10.18.13.6143]
    Language : @ID94cca2fdaccfc2cd@
    Memory :     5876MB 300KB
    OS : 6.2.9200 () 0x300-0x1 (64 bits)
    Physics : threaded
    Renderer : DX9 threaded
    Sound : Realtek Semiconductor Corp. (Speakers / Headphones (Realtek High Definition Audio))

**Comment by DrNewbie** [comment]
working fine at my here
and I don't know what is ''C++ exception'' , ''bad allocation''

**Comment by Skyfry428** [comment]
After redownloading and not messing with any files, I then got this crash. Currently verifying my game files to see if this changes anything.
Application has crashed: C++ exception
[File] Cannot read from file "C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\assets\7e3f8591e65ba48b.bundle" => error code 998: Invalid access to memory location. (d:\jenkins\shared-workspace\diesel\engine\dieselx\dieselx\blobs../utility/Archive.cpp:2487)

SCRIPT_STACK

load() @mods/BeardLib/Hooks/CoreSystem.lua:72
WorldDefinition_load_continent_package() core/lib/utils/dev/editor/coreworlddefinition.lua:169
WorldDefinition_load_continent_package() @mods/BeardLib/Hooks/CoreWorldDefinition.lua:62
_load_continent_package() @mods/BeardLib/Hooks/CoreWorldDefinition.lua:62
_insert_instances() core/lib/utils/dev/editor/coreworlddefinition.lua:266
parse_continents() core/lib/utils/dev/editor/coreworlddefinition.lua:254
init() core/lib/utils/dev/editor/coreworlddefinition.lua:40
init() lib/utils/dev/editor/worlddefinition.lua:6
new() core/lib/utils/coreclass.lua:35
init() core/lib/utils/dev/editor/worldholder.lua:49
new() core/lib/utils/coreclass.lua:35
init_game() lib/setups/gamesetup.lua:514
core/lib/setups/coresetup.lua:394
() =(tail call):-1

---

Callstack:

Cannot fetch callstack

---

Current thread: Main
Script stack:
                        load()  @mods/BeardLib/Hooks/CoreSystem.lua:72  
WorldDefinition_load_continent_package()  core/lib/utils/dev/editor/coreworlddefinition.lua:169  
WorldDefinition_load_continent_package()  @mods/BeardLib/Hooks/CoreWorldDefinition.lua:62  
     _load_continent_package()  @mods/BeardLib/Hooks/CoreWorldDefinition.lua:62  
           _insert_instances()  core/lib/utils/dev/editor/coreworlddefinition.lua:266  
            parse_continents()  core/lib/utils/dev/editor/coreworlddefinition.lua:254  
                        init()  core/lib/utils/dev/editor/coreworlddefinition.lua:40  
                        init()  lib/utils/dev/editor/worlddefinition.lua:6  
                         new()  core/lib/utils/coreclass.lua:35  
                        init()  core/lib/utils/dev/editor/worldholder.lua:49  
                         new()  core/lib/utils/coreclass.lua:35  
                   init_game()  lib/setups/gamesetup.lua:514  
                                core/lib/setups/coresetup.lua:394  
                            ()  =(tail                                              

##                       call):-1  

System information:
    Application version : 1.55.37
    CPU : Intel(R) Core(TM) i5 CPU M 480 @ 2.67GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
    DirectX : 12.0 
    GPU : Intel(R) HD Graphics / nvumdshim.dll[10.18.13.6143]
    Language : @ID94cca2fdaccfc2cd@
    Memory :     5876MB 300KB
    OS : 6.2.9200 () 0x300-0x1 (64 bits)
    Physics : threaded
    Renderer : DX9 threaded
    Sound : Realtek Semiconductor Corp. (Speakers / Headphones (Realtek High Definition Audio))

**Comment by DrNewbie** [comment]
I didn't see info that connect to this Mod.
All those messages are point to core things (worlddefinition) but this Mod only use\change\hook 1 core that do init [lua/event.lua](https://github.com/DrNewbie/Safehouse-Plus/blob/master/lua/event.lua#L18)
